### PR TITLE
Completed Flickr App

### PR DESCRIPTION
**Pull request by oguzkaganeren**
I used Chakra UI and Mobx mst.

### CODE REVIEW

**Comment by vlad-saling** [comment]
@oguzkaganeren Thank you for this PR. We'll review it shortly!

**Comment by vlad-saling** [comment]
@oguzkaganeren would it be possible to match the UI with what we have in Figma? It's a bit too far from the mockup.

**Comment by oguzkaganeren** [comment]
@vlad-saling Sorry about that. I thought It is a general concept, I will fix it quickly.

**Comment by oguzkaganeren** [comment]
I have fixed. I apologize again for my fault.

**Comment by vlad-saling** [comment]
Thank you @oguzkaganeren . Would you be open to a quick call sometimes next week? 30 minutes tops.

**Pull request closed without merging**
